### ISSUE TITLE
obsfucate passwords from being printed without a --verbose or similar switch

### ISSUE THREAD

**Issue by danielhallberg** [1Password/solutions#27]
When running the main.py script without any options, all of the passwords being imported are printed to console.   This shouldn't be the default functionality.   Not printing that field should be the default unless a switch is invoked to provide that level of detail.

**Comment by scottisloud** [comment]
This is a good call out. This is the default output for item creation with the 1Password CLI, but we have some changes coming to this script that rewrites the output to avoid printing full item details. 

Thanks for your interest and feedback!
