### ISSUE TITLE
Python `create_vaults_from_input.py` example script fails on Windows

### ISSUE THREAD

**Issue by ag-adampike** [1Password/solutions#63]
In Windows environments, `getMyUUID()` catches an error on every run of the script, even after recently signing in. The response from the `subprocess.run` implementation of 1Password CLI seems to include a non-zero return code in every case, so the script exits here:

https://github.com/1Password/solutions/blob/4e7dab5c54be2f0464099c91741a999b62e7040b/account-management/create_vaults_from_input.py#L38-L41

I've not yet been able to work out why this is an issue for Windows, but it's easily reproduced. The error message consistently includes `account not signed in`.

**Comment by scottisloud** [comment]
Does this happen both when using the desktop integration and when signing into `op` manually?

**Comment by ag-adampike** [comment]
This error happens on Windows when 1Password CLI is integrated with 1Password for Windows. The desktop app integration seems to block a subprocess from delegating sign in from the desktop app.

A workaround is to sign in manually:
https://developer.1password.com/docs/cli/sign-in-manually/

The script behaves as expected on Windows when signing in manually.
